name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: check out git repository
        uses: actions/checkout@v2

      - name: install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: install dependencies
        run: npm ci
      
      - name: lint
        run: npm run lint
